-- loadfloans.sql

DROP TABLE IF EXISTS loans;

SET SESSION sql_mode = '';

CREATE TABLE loans (
id varchar(15),
member_id varchar(15),
loan_amnt decimal(20,2),
funded_amnt decimal(20,2),
funded_amnt_inv decimal(20,2),
term varchar(15),
int_rate varchar(15),
installment decimal(20,2),
grade varchar(1),
sub_grade varchar(2),
emp_title varchar(100),
emp_length varchar(30),
home_ownership varchar(15),
annual_inc decimal(20,2),
verification_status varchar(30),
issue_d  varchar(15),
loan_status varchar(15),
pymnt_plan varchar(1),
url varchar(15),
desc_1 varchar(300),
purpose varchar(30),
title varchar(150),
zip_code varchar(5),
addr_state varchar(2),
dti decimal(20,2),
delinq_2yrs numeric(2,0),
earliest_cr_line  varchar(15),
inq_last_6mths numeric(1,0),
mths_since_last_delinq  numeric(3,0),
mths_since_last_record numeric(3,0),
open_acc numeric(2,0),
pub_rec numeric(1,0),
revol_bal decimal(20,2),
revol_util decimal(20,2),
total_acc numeric(2,0),
initial_list_status varchar(1),
out_prncp numeric(1,0),
out_prncp_inv numeric(1,0),
total_pymnt decimal(20,6),
total_pymnt_inv decimal(20,6),
total_rec_prncp decimal(20,2),
total_rec_int decimal(20,2),
total_rec_late_fee decimal(20,9),
recoveries decimal(20,2),
collection_recovery_fee decimal(20,9),
last_pymnt_d  varchar(15),
last_pymnt_amnt decimal(20,2),
next_pymnt_d  varchar(15),
last_credit_pull_d  varchar(15),
collections_12_mths_ex_med numeric(1,0),
mths_since_last_major_derog numeric(2,0),
policy_code numeric(1,0),
application_type varchar(15),
annual_inc_joint numeric(10,0),
dti_joint numeric(10,0),
verification_status_joint numeric(1,0),
acc_now_delinq numeric(1,0),
tot_coll_amt numeric(10,0),
tot_cur_bal numeric(10,0),
open_acc_6m numeric(10,0),
open_act_il numeric(10,0),
open_il_12m numeric(10,0),
open_il_24m numeric(10,0),
mths_since_rcnt_il numeric(10,0),
total_bal_il numeric(10,0),
il_util numeric(10,0),
open_rv_12m numeric(10,0),
open_rv_24m numeric(10,0),
max_bal_bc numeric(10,0),
all_util numeric(10,0),
total_rev_hi_lim numeric(10,0),
inq_fi numeric(10,0),
total_cu_tl numeric(10,0),
inq_last_12m numeric(10,0),
acc_open_past_24mths numeric(10,0),
avg_cur_bal numeric(10,0),
bc_open_to_buy numeric(10,0),
bc_util numeric(10,0),
chargeoff_within_12_mths numeric(1,0),
delinq_amnt numeric(10,0),
mo_sin_old_il_acct numeric(10,0),
mo_sin_old_rev_tl_op numeric(10,0),
mo_sin_rcnt_rev_tl_op numeric(10,0),
mo_sin_rcnt_tl numeric(10,0),
mort_acc numeric(10,0),
mths_since_recent_bc numeric(10,0),
mths_since_recent_bc_dlq numeric(10,0),
mths_since_recent_inq numeric(10,0),
mths_since_recent_revol_delinq numeric(10,0),
num_accts_ever_120_pd numeric(10,0),
num_actv_bc_tl numeric(10,0),
num_actv_rev_tl numeric(10,0),
num_bc_sats numeric(10,0),
num_bc_tl numeric(10,0),
num_il_tl numeric(10,0),
num_op_rev_tl numeric(10,0),
num_rev_accts numeric(10,0),
num_rev_tl_bal_gt_0 numeric(10,0),
num_sats numeric(10,0),
num_tl_120dpd_2m numeric(10,0),
num_tl_30dpd numeric(10,0),
num_tl_90g_dpd_24m numeric(10,0),
num_tl_op_past_12m numeric(10,0),
pct_tl_nvr_dlq numeric(10,0),
percent_bc_gt_75 numeric(10,0),
pub_rec_bankruptcies numeric(1,0),
tax_liens numeric(1,0),
tot_hi_cred_lim numeric(10,0),
total_bal_ex_mort numeric(10,0),
total_bc_limit numeric(10,0),
total_il_high_credit_limit numeric(10,0),
revol_bal_joint numeric(10,0),
sec_app_earliest_cr_line numeric(10,0),
sec_app_inq_last_6mths numeric(10,0),
sec_app_mort_acc numeric(10,0),
sec_app_open_acc numeric(10,0),
sec_app_revol_util numeric(10,0),
sec_app_open_act_il numeric(10,0),
sec_app_num_rev_accts numeric(10,0),
sec_app_chargeoff_within_12_mths numeric(10,0),
sec_app_collections_12_mths_ex_med numeric(10,0),
sec_app_mths_since_last_major_derog numeric(10,0),
hardship_flag varchar(1),
hardship_type varchar(15),
hardship_reason varchar(15),
hardship_status varchar(15),
deferral_term varchar(15),
hardship_amount numeric(10,0),
hardship_start_date  varchar(15),
hardship_end_date  varchar(15),
payment_plan_start_date date,
hardship_length numeric(10,0),
hardship_dpd numeric(10,0),
hardship_loan_status varchar(15),
orig_projected_additional_accrued_interest decimal(20,9),
hardship_payoff_balance_amount numeric(10,0),
hardship_last_payment_amount numeric(10,0),
disbursement_method varchar(15),
debt_settlement_flag varchar(1),
debt_settlement_flag_date  varchar(15),
settlement_status varchar(15),
settlement_date  varchar(15),
settlement_amount decimal(20,2),
settlement_percentage decimal(20,2),
settlement_term numeric(3,0)

  );
  
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 5.7/Uploads/flights/lending_club_loans.csv' 
INTO TABLE loans
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT 'loans', COUNT(*) FROM loans;
 
  

